print (" i am using python")
print ("i live in india")
print ("i like to play vollyball")
print ("i am learning  codeing")
print ("my sister name is linisa")
print ("i live in vikas nagar")
print ("my favourite ipl team is rcb")
print ("my favorite song was pal pal")
print ("i love to play with mud an made things frome mud")
print ("i am doing my home work")